name: tricolor-trials
base: core22
version: '0.1.4'
summary: Complete color changing laps!
description: |
  A car looper where the colored blocks change based on the lap. 

grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64

apps:
  tricolor-trials:
    command: tricolor-trials
    extensions: [gnome]
    plugs: [home, network, removable-media, unity7]

parts:
  tricolor-trials:
    plugin: dump
    source: ./builds/
    source-type: local
    stage-packages:
      - libglu1-mesa
      - libxcursor1
      - libxinerama1
      - libxrandr2
      - libxi6
      - libpulse0
    override-build: |
      snapcraftctl build
      chmod +x $SNAPCRAFT_PART_INSTALL/tricolor-trials

layout:
  /usr/share/tricolor-trials:
    bind: $SNAP/usr/share/tricolor-trials
