name: tricolor-trials
base: core22
version: '<PlaceHolderVersion>'
summary: <PlaceHolderShortDesc>
description: |
  <PlaceHolderLongDesc>

grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64

apps:
  tricolor-trials:
    command: tricolor-trials
    extensions: [gnome]
    plugs:
      - home
      - removable-media
      - network
      - opengl
      - x11
      - wayland
      - desktop
      - desktop-legacy
      - unity7
    desktop: others/snap/gui/tricolor-trials.desktop

parts:
  tricolor-trials:
    plugin: dump
    source: ./builds/
    source-type: local
    stage-packages:
      - libglu1-mesa
      - libxcursor1
      - libxinerama1
      - libxrandr2
      - libxi6
      - libpulse0
    override-build: |
      snapcraftctl build
      chmod +x $SNAPCRAFT_PART_INSTALL/tricolor-trials

layout:
  /usr/share/tricolor-trials:
    bind: $SNAP/usr/share/tricolor-trials
